### ISSUE TITLE
DOC Build Errors (convert & latex)

### ISSUE THREAD

**Issue by jacobfriedman** [didoudiaz/gprolog#1]
The default build includes a doc-required command `convert` - please advise; thanks in advance.
```
(cd ../doc; make all)
make[1]: Entering directory '/home/jacob/projects/gprolog/doc'
convert -scale 150x150 ../gprolog.ico[5] logo.eps
/bin/sh: 1: convert: not found
make[1]: *** [Makefile:75: logo.eps] Error 127
make[1]: Leaving directory '/home/jacob/projects/gprolog/doc'
make: *** [Makefile:54: doc] Error 2
```

**Comment by jacobfriedman** [comment]
Paulo Moura from Logtalk correctly suggested I install `imagemagick`.

I'm now getting this out-of-the-box:

```
(cd /usr/local/gprolog-1.5.0/lib; for i in *.a; do ranlib $i; done)
(cd ../doc; make all)
make[1]: Entering directory '/home/jacob/projects/gprolog/doc'
convert -scale 150x150 ../gprolog.ico[5] logo.eps
convert-im6.q16: InvalidImageIndex `../gprolog.ico' @ error/list.c/CloneImages/281.
convert-im6.q16: subimage specification returns no images `../gprolog.ico' @ error/constitute.c/ReadImage/642.
convert-im6.q16: attempt to perform an operation not allowed by the security policy `EPS' @ error/constitute.c/IsCoderAuthorized/408.
make[1]: *** [Makefile:75: logo.eps] Error 1
make[1]: Leaving directory '/home/jacob/projects/gprolog/doc'
make: *** [Makefile:54: doc] Error 2
```

**Comment by jacobfriedman** [comment]
Latex is also needed for the docs, I guess.
`pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)` not working:
```! LaTeX Error: Cannot determine size of graphic in logo.eps (no BoundingBox).
```

**Comment by jacobfriedman** [comment]
`./configure --without-doc-dir --without-html-dir` still builds the docs:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./gprolog.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14> (./packages.tex
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)) (./hevea.sty

! LaTeX Error: File `comment.sty' not found.
```

**Comment by jacobfriedman** [comment]
requires extra texlive package (ubuntu 19/20): 
`apt-get install texlive-latex-extra`
...
now requires `hevea`

**Comment by didoudiaz** [comment]
Hi Jacob,
the git repo only contains "sources" (most of "target" files are not present and must be built).
The doc is only needed when you do a 'make install'.
BTW: if you don't need to install gprolog, you can execute the locally compiled version with an adequate PATH. Under bash you can use the SETVARS script:
```
cd src
. SETVARS
make
gprolog
```
To compile the doc, you need the convert utility (from ImageMagick) to create logo files. It is extracted from the icon file (with an index). There is a version of ImageMagick containing a bug on the index of the icon to extract (some versions seem to count from 0, others from 1). Anyway, I plan to add the logo files so convert will not be needed. However, you need LaTeX and HeVeA.

**Comment by jacobfriedman** [comment]
https://github.com/didoudiaz/gprolog/issues/2
