### ISSUE TITLE
./configure --without flags unsupported

### ISSUE THREAD

**Issue by jacobfriedman** [didoudiaz/gprolog#2]
I encountered problems in the build (last issue) since I couldn't `make install` out-of-the-box. I tried the --without-doc-dir but there's actually no flag in the `src/configure.in` to support the following `--without` prefix for the following flags:
```
--without-links-dir
--without-doc-dir
--without-html-dir
--without-examples-dir
```
If I'm going to be working on a docker-wasm output, it would be nice for these flags to work.

I'll build locally with the required packages at the moment, but will have to eventually update the `src/configure.in` to support the `--without` flags to support a leaner build.

**Comment by didoudiaz** [comment]
As I said in #1 you can use the SETVARS script.
You can also do an in-place installation. In this case the directories bin lib include are created inside the repo. For this try:
```
./configure --with-install-dir=in-place
make
make install
```

**Comment by jacobfriedman** [comment]
Thank you very much. I was looking at in-place but figured I may as well report just to keep anyone in-the-know. Will close both issues.
