### ISSUE TITLE
Built-in predicate request: copy_file/2

### ISSUE THREAD

**Issue by pmoura** [didoudiaz/gprolog#23]
Would it be possible to add a `copy_file/2` predicate?

**Comment by didoudiaz** [comment]
Done (you can also test the Windows version with copy_file/2, in unstable pick setup-gprolog-1.5.1-msvc-x64.exe)

**Comment by pmoura** [comment]
Thanks! Will test on both macOS and Windows and report back.

**Comment by pmoura** [comment]
Update the Logtalk `os` library to use the new predicate when available. Tests pass on both macOS and Windows 10.
