### ISSUE TITLE
Using gplc on Windows 10

### ISSUE THREAD

**Issue by pmoura** [didoudiaz/gprolog#24]
I'm trying to use `gplc` on Windows 10. GNU Prolog was installed using the latest `setup-gprolog-1.5.1-msvc-x64.exe` beta installer. The `gplc` command is being called from a new Logtalk PowerShell [embedding script](https://github.com/LogtalkDotOrg/logtalk3/tree/master/scripts/embedding/gprolog). The same [embedding examples](https://github.com/LogtalkDotOrg/logtalk3/blob/master/scripts/embedding/SCRIPT.txt) that work e.g. in macOS, on Windows 10 end with a `compilation failed` message with no hint of what went wrong. Is there a dependency that I may be missing on Windows 10 that's required for successfully using `gplc`? Any suggestions on how to diagnose this issue?

**Comment by didoudiaz** [comment]
Things are more complex on Windows. Sorry.
First, to run gplc, you need to set your PATH to include gplc, pl2wam and other utilities in bin (e.g. add C:\GNU-Prolog\bin to PATH).
Second, you also need to install the C compiler toolchain used by your version (MSVC or MSYS2 gcc depending on the setup installer you chose - here it seems it is MSVC). You'll find more information in src/WINDOWS about how to install them.

**Comment by pmoura** [comment]
> Things are more complex on Windows. Sorry.

I blame Bill 😛

> First, to run gplc, you need to set your PATH to include gplc, pl2wam and other utilities in bin (e.g. add C:\GNU-Prolog\bin to PATH).

Was already done.

> Second, you also need to install the C compiler toolchain used by your version (MSVC or MSYS2 gcc depending on the setup installer you chose - here it seems it is MSVC). You'll find more information in src/WINDOWS about how to install them.

Thanks. It seems that I may not have all MSVC components installed. But I was aware of the need to set environment variables to use MSVC.

**Comment by pmoura** [comment]
I have been unable to successfully setup the MSVC environment for use from within PowerShell. But I'm confident that the new Logtalk embedding script is functional.If anyone can try it and report back, that would be much appreciated.
