### ISSUE TITLE
bagof/3 Segmentation fault

### ISSUE THREAD

**Issue by flexoron** [didoudiaz/gprolog#28]
```
$ gprolog
GNU Prolog 1.5.1 (64 bits)
Compiled May  7 2022, 16:09:46 with gcc
Copyright (C) 1999-2022 Daniel Diaz

| ?- bagof(X,X^!=X,Y).
Segmentation fault (core dumped)
```

**Comment by pmoura** [comment]
The query creates a singleton list containing a cyclic term. But cyclic terms are currently not supported.

**Comment by flexoron** [comment]
@pmoura You can't say that. In a narrow sense cyclic terms are supported, namely otherwise identified:

| ?- X^!=X.
cannot display cyclic term for X

**Comment by pmoura** [comment]
Support for cyclic terms (aka rational trees) require being able to (1) create cyclic terms, (2) unify cyclic terms, and (3) display bindings that contain cyclic terms. Your query above shows (3) to not be possible. A query such as:

```text
| ?- X = f(X), Y = f(Y), X = Y.
```

shows that (2) is also not possible. Thus, if you only have (1), i.e. you can create cyclic terms but you can't actually do anything useful with them, saying that "cyclic terms are currently not supported" is a fair description.

**Comment by flexoron** [comment]
Seriously? Segmentation faults are not acceptable! In no way!

**Comment by flexoron** [comment]
Another example:
```
| ?- X = (\+X).

cannot display cyclic term for X

yes

| ? X = (\+X), write(X).
\+ \+ \+ \+ \+ \+ \+ \+ \+ \+ \+ \+ \+ \+ \+ \+ \+
:
:
\+ \+ \+ \+ \+ \+Segmentation fault (core dumped)

$
```

**Comment by didoudiaz** [comment]
See issue #34
