### ISSUE TITLE
Attempting to build on Termux

### ISSUE THREAD

**Issue by MikeAmy** [didoudiaz/gprolog#3]
I saw you added ARM support and thought it would be cool if gprolog could run on the Termux platform (maybe this is a low-hanging fruit). So I attempted to build it to see what falls out. 

Errors: (copied from below)

engine1.c:137:9: error: invalid symbol kind for ADRP relocation
    asm("adrp x20, _pl_reg_bank@GOTPAGE");
        ^
<inline asm>:1:2: note: instantiated into assembly here
        adrp x20, _pl_reg_bank@GOTPAGE
        ^
engine1.c:138:9: error: invalid fixup for 64-bit load/store instruction
    asm("ldr  x20, [x20, _pl_reg_bank@GOTPAGEOFF]");
        ^
<inline asm>:1:2: note: instantiated into assembly here
        ldr  x20, [x20, _pl_reg_bank@GOTPAGEOFF]
        ^

I am building on an android 11 device using termux version 0.112

$ ./configure

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for as... as
checking for ranlib... ranlib
checking for windres... no
checking for ar... ar
checking for strip... strip
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /data/data/com.termux/files/usr/bin/install -c
checking whether ln -s works... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /data/data/com.termux/files/usr/bin/grep
checking for egrep... /data/data/com.termux/files/usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking size of int... 4
checking size of long... 8
checking size of void*... 8
checking sys/ioctl_compat.h usability... no
checking sys/ioctl_compat.h presence... no
checking for sys/ioctl_compat.h... no
checking sys/siginfo.h usability... no
checking sys/siginfo.h presence... no
checking for sys/siginfo.h... no
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking sys/endian.h usability... yes
checking sys/endian.h presence... yes
checking for sys/endian.h... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for getpagesize... (cached) yes
checking for mprotect... yes
checking for sigaction... yes
checking for mallopt... yes
checking for fgetc... yes
checking whether htole32 is declared... yes
checking whether bswap_32 is declared... yes
checking for fpclass... no
checking for _fpclass... no
checking for isnan... yes
checking for isinf... yes
checking for atanh... yes
checking for acosh... yes
checking for asinh... yes
checking for socklen_t... yes
checking if struct sigcontext needs asm/sigcontext.h... no
checking for sigsetjmp... yes
checking for a working sigaction... yes
checking constructors execution order... first to last
checking for socket... yes
checking for gethostbyname... yes
DIRECTORIES
--> Installation:       /usr/local/gprolog-1.5.0
--> Link to binaries:   /usr/local/bin
--> Documentation:      /usr/local/gprolog-1.5.0/doc
--> HTML documentation: /usr/local/gprolog-1.5.0/doc/html_node
--> Examples:           /usr/local/gprolog-1.5.0/examples
./configure: 6698: cannot create /tmp/version_no.tex: Directory nonexistent
mv: cannot stat '/tmp/version_no.tex': No such file or directory
./configure: 6705: cannot create /tmp/copyright.tex: Directory nonexistent
mv: cannot stat '/tmp/copyright.tex': No such file or directory
configure: creating ./config.status
config.status: creating Makefile
config.status: creating TopComp/Makefile
config.status: creating Pl2Wam/Makefile
config.status: creating Wam2Ma/Makefile
config.status: creating Ma2Asm/Makefile
config.status: creating Fd2C/Makefile
config.status: creating Linedit/Makefile
config.status: creating W32GUICons/Makefile
config.status: creating EnginePl/Makefile
config.status: creating BipsPl/Makefile
config.status: creating EngineFD/Makefile
config.status: creating BipsFD/Makefile
config.status: creating Ma2Asm/FromC/Makefile
config.status: creating Win32/Makefile
config.status: creating Win32/gp-vars-iss.txt
config.status: creating EnginePl/gp_config.h
config.status: EnginePl/gp_config.h is unchanged

$ make

cd EnginePl; make config
make[1]: Entering directory '/data/data/com.termux/files/home/Projects/gnuprolog/gprolog/src/EnginePl'
gcc  -fno-strict-aliasing -fcommon -O3 -fomit-frame-pointer -Wno-char-subscripts  -o pl_config pl_config.c
./pl_config

	-------------------------------
	--- GNU PROLOG INSTALLATION ---
	-------------------------------

GNU Prolog version: 1.5.0 (Jun  5 2021)
Operating system  : linux-gnu
Processor         : aarch64
Size of a WAM word: 64 bits
C compiler        : gcc
C flags           : -O3 -fomit-frame-pointer -Wno-char-subscripts
C flags machine   :  -fno-strict-aliasing -fcommon
Assembler         : as
Assembler flags   : 
Loader flags      : 
Loader libraries  : -lm
Use line editor   : Yes
Use piped consult : Yes
Use sockets       : Yes
Use FD solver     : Yes
Use machine regs. : Yes (0 used)
Used register(s)  : none

	------------------------------

(cd ../TopComp; make gplc)
make[2]: Entering directory '/data/data/com.termux/files/home/Projects/gnuprolog/gprolog/src/TopComp'
gcc  -fno-strict-aliasing -fcommon -O3 -fomit-frame-pointer -Wno-char-subscripts -o gplc top_comp.c -lm
make[2]: Leaving directory '/data/data/com.termux/files/home/Projects/gnuprolog/gprolog/src/TopComp'
make[1]: Leaving directory '/data/data/com.termux/files/home/Projects/gnuprolog/gprolog/src/EnginePl'
. ./SETVARS;for i in EnginePl TopComp Wam2Ma Ma2Asm Linedit BipsPl Pl2Wam Fd2C EngineFD BipsFD;do (cd $i; make) || exit 1; done;\
(cd TopComp; make top-level) || exit 1;\
(cd Pl2Wam; make stage2)
make[1]: Entering directory '/data/data/com.termux/files/home/Projects/gnuprolog/gprolog/src/EnginePl'
gcc  -fno-strict-aliasing -fcommon -O3 -fomit-frame-pointer -Wno-char-subscripts  -o cpp_headers cpp_headers.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' machine.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' machine1.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' stacks_sigsegv.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' mem_alloc.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' misc.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' hash_fct.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' hash.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' obj_chain.c
gplc -c -C '-O3 -fomit-frame-pointer -Wno-char-subscripts' engine.c
gplc -c -o engine1.o engine1.c
engine1.c:137:9: error: invalid symbol kind for ADRP relocation
    asm("adrp x20, _pl_reg_bank@GOTPAGE");
        ^
<inline asm>:1:2: note: instantiated into assembly here
        adrp x20, _pl_reg_bank@GOTPAGE
        ^
engine1.c:138:9: error: invalid fixup for 64-bit load/store instruction
    asm("ldr  x20, [x20, _pl_reg_bank@GOTPAGEOFF]");
        ^
<inline asm>:1:2: note: instantiated into assembly here
        ldr  x20, [x20, _pl_reg_bank@GOTPAGEOFF]
        ^
2 errors generated.
compilation failed
make[1]: *** [Makefile:83: engine1.o] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/Projects/gnuprolog/gprolog/src/EnginePl'
make: *** [Makefile:45: all] Error 1

**Comment by didoudiaz** [comment]
This is due to Termux which uses clang (actually gcc is an alias to clang).
On linux, the C compiler expected is gcc. On Termux gcc is an alias to clang.
on linux clang and gcc does not handle symbols in the same way (hence the error about pl_reg_bank which does not need a leading underscore).
I did the necessary modification to hanlde both compilers on linux (and on macos).
Can you try it on Termux ?

BTW to specify a given compiler you can use:
```
$ cd src
$ . SETVARS
$ CC=clang ./configure
$ make
$ gprolog
```

**Comment by didoudiaz** [comment]
The problem comes from the general `make install` which also installs the doc. This repo only contains the source LaTeX files of the doc which can be compiled with `make doc`. However, this requires several several tools: latex, hevea (see doc/README). 

Since the doc is not mandatory, my advice would be to simply forget it. For this configure with:

`$ ./configure --with-doc-dir=none --with-examples-dir=none --prefix=$PREFIX`
you should see something like (with the correct termux prefix instead of `/tmp/foo`):
```
DIRECTORIES
--> Installation:       /tmp/foo/gprolog-1.5.0
--> Link to binaries:   /tmp/foo/bin
--> Documentation:      none
--> HTML documentation: none
--> Examples:           none
configure: creating ./config.status
```
then `make install` will only install the base system and create links to the binairies.

Thank you for your proposal to build a termux package. The arm version will be stable. Note that 1.5.0 is not yet officially released. My advice would be to prepare the package and wait for the official release (check [www.gprolog.org](https://www.gprolog.org))
