### ISSUE TITLE
Likely simple bugs to fix in the format/2-3 predicates

### ISSUE THREAD

**Issue by pmoura** [didoudiaz/gprolog#37]
Bug in the implementation of `~c` (code): the following calls are expected to print  an `A`:

```text
| ?- format("~c", [65]).

yes
| ?- format('~c', [65]).

yes
```

Bug in the implementation of `~i` (ignore): the following calls are expected to omit the middle argument and thus print `ac`:

```text
| ?- format("~a~i~a", [a,b,c]).
ab

yes
| ?- format('~a~i~a', [a,b,c]).
ab

yes
```

**Comment by spabreu** [comment]
Hi Paulo,

> Bug in the implementation of ~c (code): the following calls are expected to print an A:
> | ?- format("~c", [65]).
> 
> yes
> | ?- format('~c', [65]).
> 
> yes
> 

In this case, I don’t think there's a bug:

| ?- format("~c", [65]), flush_output.
A

yes

cheers,
-spa

**Comment by pmoura** [comment]
Hi Salvador.

Interesting. But other Prolog systems don't require a call to `flush_output/0` (or `flush_output/1` for `format/3` calls).

**Comment by pmoura** [comment]
Additionally, the test definition implicitly closes the output stream, which is expected to flush any pending output.

**Comment by pmoura** [comment]
Fixes confirmed. Thanks!
