### ISSUE TITLE
Detecting errors in format/2-3 goals

### ISSUE THREAD

**Issue by pmoura** [didoudiaz/gprolog#38]
Excluding the table related format specifiers, the only other `format/2-3` test failures we now have are in the detection of errors in goals. The tests are:

```logtalk

test(lgt_format_2_partial_list_second_argument_1, error(instantiation_error)) :-
	^^set_text_output(''),
	{format("~d", [42| _])}.

test(lgt_format_2_too_many_arguments_1, errors([domain_error(_,_), consistency_error(_,_,_)])) :-
	^^set_text_output(''),
	{format("abc", [def])}.

test(lgt_format_2_too_many_arguments_2, errors([domain_error(_,_), consistency_error(_,_,_)])) :-
	^^set_text_output(''),
	{format("~a ~d", [abc, 42, def])}.
```

For the last two, there isn't a de facto standard exception. Most systems (that detect these errors), due use a domain error. E.g. in LVM:

```text
?- format("~a ~d", [abc, 42, def]).
uncaught exception: error(domain_error(expected_number_of_arguments,[abc,42,def]),format([126,97,32,126,100],[abc,42,def]))
```

In Trealla Prolog:

```text
?- format("~a ~d", [abc, 42, def]).
   error(domain_error(empty_list,[def]),format/2).
```

**Comment by didoudiaz** [comment]
for the 2 last cases, I prefer simply domain_error(number_of_arguments,...)

**Comment by pmoura** [comment]
That's also a reasonable choice. The best choice will be, however, a **standard** `consistency_error(...)`. SICStus Prolog provides it but, besides not being standard, I'm not happy with its spec in some uses cases.

**Comment by pmoura** [comment]
Fix confirmed. Thanks.
