### ISSUE TITLE
directory_files/2 predicate broken on Windows?

### ISSUE THREAD

**Issue by pmoura** [didoudiaz/gprolog#4]
I'm testing GNU Prolog 1.5.0 (x86_64 / Windows 10 with MSVC++) on Windows 10. No matter the path I pass as first argument, I always get a `error(system_error('No such file or directory'), directory_files/2)` or `error(system_error('No error'),directory_files/2)` exceptions.

**Comment by pmoura** [comment]
Same issue with the Windows 10 with MinGW64 gcc under MSys2 build.

**Comment by pmoura** [comment]
More details:

```text
GNU Prolog 1.5.0 (64 bits)
Compiled Jul  8 2021, 12:22:53 with gcc
Copyright (C) 1999-2021 Daniel Diaz

| ?- current_directory(D).
uncaught exception: error(existence_error(procedure,current_directory/1),top_level/0)
| ?- working_directory(D).

D = 'C:\\GNU-Prolog\\bin'

yes
| ?- directory_files('C:\\GNU-Prolog\\bin', Files).

Files = ['.',..,'create_bat.exe','fd2c.exe','gplc.exe','gprolog.exe','hexgplc.exe','ma2asm.exe','pl2wam.exe','w32guicons.dll','wam2ma.exe','yasm-win64.exe']

yes
| ?- directory_files('C:/GNU-Prolog/bin', Files).

Files = ['.',..,'create_bat.exe','fd2c.exe','gplc.exe','gprolog.exe','hexgplc.exe','ma2asm.exe','pl2wam.exe','w32guicons.dll','wam2ma.exe','yasm-win64.exe']

yes
```

But if I start Logtalk using the "Logtalk - GNU Prolog" shortcut:

```text
| ?- directory_files('C:\\GNU-Prolog\\bin', Files).
uncaught exception: error(system_error('No error'),directory_files/2)
| ?- directory_files('C:/GNU-Prolog/bin', Files).
uncaught exception: error(system_error('No error'),directory_files/2)
```

The only change to GNU Prolog defaults when running Logtalk is that the `strict_iso` flag is turned off. But toggling this flag doesn't solve the problem. On the other hand, if I start GNU-Prolog and then load Logtalk from the top-level:

```text
| ?- ['C:/Program Files (x86)/Logtalk/integration/logtalk_gp.pl'].
...
Logtalk 3.49.0-b05
Copyright (c) 1998-2021 Paulo Moura
...

(468 ms) yes
| ?- directory_files('C:\\GNU-Prolog\\bin', Files).

Files = ['.',..,'create_bat.exe','fd2c.exe','gplc.exe','gprolog.exe','hexgplc.exe','ma2asm.exe','pl2wam.exe','w32guicons.dll','wam2ma.exe','yasm-win64.exe']

yes
| ?- directory_files('C:/GNU-Prolog/bin', Files).

Files = ['.',..,'create_bat.exe','fd2c.exe','gplc.exe','gprolog.exe','hexgplc.exe','ma2asm.exe','pl2wam.exe','w32guicons.dll','wam2ma.exe','yasm-win64.exe']

yes
```

Thus, the issue seems to be caused by how Logtalk with GNU Prolog is started. If from a Windows shortcut, `directory_files/2` doesn't work. If we start GNU Prolog directly and then load Logtalk, `directory_files/2` works as expected.

**Comment by pmoura** [comment]
Running the integration shortcut as an administrator doesn't solve the problem.

**Comment by pmoura** [comment]
The issue can be solved by editing the shortcut properties and then set compatibility mode to Windows 7.

**Comment by pmoura** [comment]
Actually, setting the shortcut compatibility mode, sets the GNU Prolog executable itself compatibility mode. Thus, it seems that the GNU Prolog installers for Windows need to ensure that the compatibility mode is set to Windows 7.

**Comment by didoudiaz** [comment]
I could reproduce this strange behavior and I have no explanations why this occurs now. The problem comes from the use of _findfirst/_findnext (other projects report the same problem). 
 I confirm that turning the compatibility mode on is a workaround (after some tries, even comptatibility set to Windows 8 worked).
In next release, I'll try to use other system calls (FindFirstFile/FindNextFile) to implement directory_files.

**Comment by pmoura** [comment]
The trick of setting the compatibility mode to Windows 7 or 8 no longer works in recent Windows 10 builds. I'm working on a portable package manager that requires a call to the `directory_files/2` predicate at startup. This bug effectively prevents running the next Logtalk release with GNU Prolog on Windows 10.

**Comment by pmoura** [comment]
Fix confirmed using the Windows build you provided at http://www.gprolog.org/unstable/ Thanks!

**Comment by abijah97** [comment]
Hey,I'm having the same problem as that of Pmoura above there,that was 2022 I guess,need help please,
