### ISSUE TITLE
Support for call_nth/2

### ISSUE THREAD

**Issue by UWN** [didoudiaz/gprolog#43]
```
| ?- call_nth(repeat,Nth). 
uncaught exception: error(existence_error(procedure,call_nth/2),top_level/0)
```
Note that without [`call_nth/2`](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/call_nth) testing is practically impossible.

**Comment by didoudiaz** [comment]
Implemented (cf. last commit).
