### ISSUE TITLE
Misleading error for inexistent file

### ISSUE THREAD

**Issue by UWN** [didoudiaz/gprolog#44]
<pre>
ulrich@p0:/tmp$ export PATH=/opt/gupu/gprolog-1.6.0/bin:${PATH} ; /opt/gupu/gprolog-1.6.0/bin/gprolog  --consult-file inexistant
GNU Prolog 1.6.0 (64 bits)
Compiled Jun 26 2023, 07:25:57 with gcc -std=gnu11
Copyright (C) 1999-2023 Daniel Diaz

warning: command-line consulting file inexistant failed due to <strong>existence_error(procedure,'$consult2'/1)</strong>
| ?- open(inexistant,read,S).
uncaught exception: error(existence_error(source_sink,inexistant),open/3)
</pre>

This error suggests that `$consult2/1` is not defined when in fact, the file is not existing.

**Comment by didoudiaz** [comment]
Thanks for the report. Fixed.
