### ISSUE TITLE
Installation: somehow the date in banner is not changed

### ISSUE THREAD

**Issue by UWN** [didoudiaz/gprolog#52]
Even after a make clean...

**Comment by didoudiaz** [comment]
Run:
```
./configure
make
```

**Comment by UWN** [comment]
For each update?

**Comment by didoudiaz** [comment]
It should be executed at each update. However, `./configure` checks host system features and outputs some files with these results + some directories, dates,... If you omit it, it keeps what has been set by the last `./configure` (generally this works except if you updated your system with new libs,...). Keeping things as is also keeps the date (displayed in banner). Maybe I will change this (I have to check where/when it is used).

**Comment by UWN** [comment]
Ideally, the banner would also be bit more verbose about the exact version. Currently, after each `git pull`, there is only 1.6.0 as version number. The output of `git describe` would help. Which is currently `v1.5.0-119-g004cbf1`
