### ISSUE TITLE
X #= 1.1*1.1 Evaluability

### ISSUE THREAD

**Issue by jacobfriedman** [didoudiaz/gprolog#6]
I'm trying to find an ISO system (free / non-sicstus) that can handle the problem of 
`X #= 1.1*1.1`.

The [BNR system](https://github.com/ridgeworks/clpBNR) is useful in that it provides an answer, whereby GNU does not:

- If trying to use FD, which isn't ideal for this case:`uncaught exception: error(type_error(fd_evaluable,1.1000000000000001),(#=)/2)`
-  1.21 =:= 1.1*1.1.  (yields 'no').

What should be done about this?

Thank you - and I hear v2 may be coming out soon ;)

**Comment by didoudiaz** [comment]
What you need is a solver over reals (GNU Prolog provides a solver over finite integers).
You can look at the clpr library (provided in SWI Prolog)

**Comment by jacobfriedman** [comment]
Thank you! I'm looking at BNR- very interesting. Take care.
